/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/388oIlpdj68
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from '@/components/ui/button'
import { DialogTrigger, DialogTitle, DialogHeader, DialogContent, Dialog } from '@/components/ui/dialog'
import { Label } from '@/components/ui/label'
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from '@/components/ui/select'

export function AppSettings() {
  return (
    <div className="grid gap-6 py-4">
      <div className="grid gap-2 text-left">
        <Label htmlFor="currency">Currency</Label>
        <Select defaultValue="usd">
          <SelectTrigger className="w-full">
            <SelectValue placeholder="Select currency" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="usd">USD</SelectItem>
            <SelectItem value="eur">EUR</SelectItem>
            <SelectItem value="gbp">GBP</SelectItem>
            <SelectItem value="jpy">JPY</SelectItem>
            <SelectItem value="cad">CAD</SelectItem>
          </SelectContent>
        </Select>
        <Button
          variant="outline"
          className="bg-cherry_medium-700 hover:bg-cherry_medium-800  border-none font-nunito_sans text-black"
        >
          Save Currency
        </Button>
      </div>
      <div className="grid gap-2 text-left">
        <Label>Install App</Label>
        <div className="flex flex-col gap-2">
          <Button variant="outline">
            <DownloadIcon className="mr-2 h-4 w-4" />
            {`Download PWA <3`}
          </Button>
        </div>
      </div>
    </div>
  )
}

function DownloadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
